#pragma once

/**
 * @file fpr_config.h
 * @brief FPR Configuration Definitions
 * 
 * This header maps Kconfig options to FPR configuration macros.
 * All timing, debug, and behavior settings are controlled via
 * ESP-IDF's menuconfig system (idf.py menuconfig).
 * 
 * Configuration Categories:
 * - Channel: WiFi channel selection
 * - Power: Low power mode settings
 * - Queue: Receive queue behavior
 * - Timing: Connection timeouts and intervals
 * - Debug: Logging verbosity
 * - Task: FreeRTOS task parameters
 * 
 * @version 1.0.0
 * @date December 2025
 * @see Kconfig.projbuild for available options
 */

#include "sdkconfig.h"

// Channel configuration
#ifndef CONFIG_FPR_WIFI_CHANNEL
#define FPR_WIFI_CHANNEL 0
#else
#define FPR_WIFI_CHANNEL CONFIG_FPR_WIFI_CHANNEL
#endif

// Power management - uses numeric values to avoid circular dependency with fpr_def.h
// 0 = FPR_POWER_NORMAL, 1 = FPR_POWER_LOW
#ifdef CONFIG_FPR_POWER_MODE_LOW
#define FPR_DEFAULT_POWER_MODE 1  // FPR_POWER_LOW
#define FPR_LOW_POWER_MULTIPLIER CONFIG_FPR_LOW_POWER_MULTIPLIER
#else
#define FPR_DEFAULT_POWER_MODE 0  // FPR_POWER_NORMAL
#define FPR_LOW_POWER_MULTIPLIER 4  // Default multiplier if using API to switch to low power
#endif

// Queue mode configuration
// 0 = FPR_QUEUE_MODE_NORMAL, 1 = FPR_QUEUE_MODE_LATEST_ONLY
#ifdef CONFIG_FPR_QUEUE_MODE_LATEST_ONLY_DEFAULT
#define FPR_DEFAULT_QUEUE_MODE 1  // FPR_QUEUE_MODE_LATEST_ONLY
#else
#define FPR_DEFAULT_QUEUE_MODE 0  // FPR_QUEUE_MODE_NORMAL
#endif

#define FPR_ENABLE_LEGACY_PROTOCOL CONFIG_FPR_ENABLE_LEGACY_PROTOCOL
#define FPR_RECONNECT_TASK_CORE_PIN_VALUE CONFIG_FPR_RECONNECT_TASK_CORE_PIN_VALUE
#define FPR_QUEUE_SEND_TIMEOUT_MS CONFIG_FPR_QUEUE_SEND_TIMEOUT_MS
#define FPR_BROADCAST_RETRY_INTERVAL_MS CONFIG_FPR_BROADCAST_RETRY_INTERVAL_MS
#define FPR_CLIENT_CONNECTION_MAX_WAIT_MS CONFIG_FPR_CLIENT_CONNECTION_MAX_WAIT_MS
#define FPR_CLIENT_BROADCAST_INTERVAL_MS CONFIG_FPR_CLIENT_BROADCAST_INTERVAL_MS
#define FPR_CLIENT_WAIT_CHECK_INTERVAL_MS CONFIG_FPR_CLIENT_WAIT_CHECK_INTERVAL_MS
#define FPR_MANUAL_CONNECT_RETRY_INTERVAL_MS CONFIG_FPR_MANUAL_CONNECT_RETRY_INTERVAL_MS
#define FPR_HOST_SCAN_BROADCAST_INTERVAL_MS CONFIG_FPR_HOST_SCAN_BROADCAST_INTERVAL_MS
#define FPR_HOST_SCAN_POLL_INTERVAL_MS CONFIG_FPR_HOST_SCAN_POLL_INTERVAL_MS
#define FPR_RECONNECT_TIMEOUT_MS CONFIG_FPR_RECONNECT_TIMEOUT_MS
#define FPR_KEEPALIVE_INTERVAL_MS CONFIG_FPR_KEEPALIVE_INTERVAL_MS
#define FPR_DEBUG CONFIG_FPR_DEBUG
#define FPR_TASK_PRIORITY CONFIG_FPR_TASK_PRIORITY
#define FPR_TASK_STACK_SIZE CONFIG_FPR_TASK_STACK_SIZE
#define FPR_DEBUG_LOG_CLIENT_DATA_RECEIVE CONFIG_FPR_DEBUG_LOG_CLIENT_DATA_RECEIVE
#define FPR_DEBUG_LOG_HOST_DATA_RECEIVE CONFIG_FPR_DEBUG_LOG_HOST_DATA_RECEIVE
#define FPR_DEBUG_LOG_EXTENDER_DATA_RECEIVE CONFIG_FPR_DEBUG_LOG_EXTENDER_DATA_RECEIVE