#pragma once

/**
 * @file sprout_config.h
 * @brief FPR Configuration Definitions
 * 
 * This header maps Kconfig options to FPR configuration macros.
 * All timing, debug, and behavior settings are controlled via
 * ESP-IDF's menuconfig system (idf.py menuconfig).
 * 
 * Configuration Categories:
 * - Channel: WiFi channel selection
 * - Power: Low power mode settings
 * - Queue: Receive queue behavior
 * - Timing: Connection timeouts and intervals
 * - Debug: Logging verbosity
 * - Task: FreeRTOS task parameters
 * 
 * @version 1.0.0
 * @date December 2025
 * @see Kconfig.projbuild for available options
 */

#include "sdkconfig.h"

// Channel configuration
#ifndef CONFIG_SPROUT_WIFI_CHANNEL
#define SPROUT_WIFI_CHANNEL 0
#else
#define SPROUT_WIFI_CHANNEL CONFIG_SPROUT_WIFI_CHANNEL
#endif

// Power management - uses numeric values to avoid circular dependency with sprout_def.h
// 0 = SPROUT_POWER_NORMAL, 1 = SPROUT_POWER_LOW
#ifdef CONFIG_SPROUT_POWER_MODE_LOW
#define SPROUT_DEFAULT_POWER_MODE 1  // SPROUT_POWER_LOW
#define SPROUT_LOW_POWER_MULTIPLIER CONFIG_SPROUT_LOW_POWER_MULTIPLIER
#else
#define SPROUT_DEFAULT_POWER_MODE 0  // SPROUT_POWER_NORMAL
#define SPROUT_LOW_POWER_MULTIPLIER 4  // Default multiplier if using API to switch to low power
#endif

// Queue mode configuration
// 0 = SPROUT_QUEUE_MODE_NORMAL, 1 = SPROUT_QUEUE_MODE_LATEST_ONLY
#ifdef CONFIG_SPROUT_QUEUE_MODE_LATEST_ONLY_DEFAULT
#define SPROUT_DEFAULT_QUEUE_MODE 1  // SPROUT_QUEUE_MODE_LATEST_ONLY
#else
#define SPROUT_DEFAULT_QUEUE_MODE 0  // SPROUT_QUEUE_MODE_NORMAL
#endif

#define SPROUT_ENABLE_LEGACY_PROTOCOL CONFIG_SPROUT_ENABLE_LEGACY_PROTOCOL
#define SPROUT_RECONNECT_TASK_CORE_PIN_VALUE CONFIG_SPROUT_RECONNECT_TASK_CORE_PIN_VALUE
#define SPROUT_QUEUE_SEND_TIMEOUT_MS CONFIG_SPROUT_QUEUE_SEND_TIMEOUT_MS
#define SPROUT_BROADCAST_RETRY_INTERVAL_MS CONFIG_SPROUT_BROADCAST_RETRY_INTERVAL_MS
#define SPROUT_CLIENT_CONNECTION_MAX_WAIT_MS CONFIG_SPROUT_CLIENT_CONNECTION_MAX_WAIT_MS
#define SPROUT_CLIENT_BROADCAST_INTERVAL_MS CONFIG_SPROUT_CLIENT_BROADCAST_INTERVAL_MS
#define SPROUT_CLIENT_WAIT_CHECK_INTERVAL_MS CONFIG_SPROUT_CLIENT_WAIT_CHECK_INTERVAL_MS
#define SPROUT_MANUAL_CONNECT_RETRY_INTERVAL_MS CONFIG_SPROUT_MANUAL_CONNECT_RETRY_INTERVAL_MS
#define SPROUT_HOST_SCAN_BROADCAST_INTERVAL_MS CONFIG_SPROUT_HOST_SCAN_BROADCAST_INTERVAL_MS
#define SPROUT_HOST_SCAN_POLL_INTERVAL_MS CONFIG_SPROUT_HOST_SCAN_POLL_INTERVAL_MS
#define SPROUT_RECONNECT_TIMEOUT_MS CONFIG_SPROUT_RECONNECT_TIMEOUT_MS
#define SPROUT_KEEPALIVE_INTERVAL_MS CONFIG_SPROUT_KEEPALIVE_INTERVAL_MS
#define SPROUT_DEBUG CONFIG_SPROUT_DEBUG
#define SPROUT_TASK_PRIORITY CONFIG_SPROUT_TASK_PRIORITY
#define SPROUT_TASK_STACK_SIZE CONFIG_SPROUT_TASK_STACK_SIZE
#define SPROUT_DEBUG_LOG_CLIENT_DATA_RECEIVE CONFIG_SPROUT_DEBUG_LOG_CLIENT_DATA_RECEIVE
#define SPROUT_DEBUG_LOG_HOST_DATA_RECEIVE CONFIG_SPROUT_DEBUG_LOG_HOST_DATA_RECEIVE
#define SPROUT_DEBUG_LOG_EXTENDER_DATA_RECEIVE CONFIG_SPROUT_DEBUG_LOG_EXTENDER_DATA_RECEIVE